# Generated by Django 5.0.6 on 2024-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='order_confirm',
        ),
    ]
