# Generated by Django 5.0.6 on 2024-05-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_facture_order_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='user',
        ),
    ]
